name: CI build and test

on: [pull_request]

jobs:
  build:
    name: "Build, lint and test"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        ref: master
    - run: git pull
    - run: git checkout ${{github.head_ref}}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: yarn lint
      env:
        CI: true
